### ISSUE TITLE
dbunit 2.7.3 breaks extension

### ISSUE THREAD

**Issue by jnewton03** [liquibase/liquibase-oracle#107]
After the dependabot PR was merged to upgrade dbunit from 2.7.2 to 2.7.3 the `release extension` job started to fail:
https://github.com/liquibase/liquibase-oracle/actions/runs/2577971287

Here are the changes:
http://dbunit.sourceforge.net/dbunit/changes-report.html#a2.7.3

This issue should be used to track 2 things:
1. fixing our dependency issue
2. updating our pull request action to catch issues like this.  The PR was green but obviously had breaking changes.

CC @nvoxland @molivasdat @kevin-atx

**Comment by filipelautert** [comment]
Hello - it is fixed now, releases are working again.
