### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by ramarro123** [liquibase/liquibase-oracle#119]
Where I can found updated doc? The liquibase.page.seems very outdated.

**Comment by filipelautert** [comment]
Hello @ramarro123 - I think the best location would be https://docs.liquibase.com/start/install/tutorials/oracle.html . And then the very old documentation at https://liquibase.jira.com/wiki/spaces/CONTRIB/pages/3112975/Oracle+Extensions .

**Comment by ramarro123** [comment]
hi @filipelautert the first link doesn't have any docs about the added change types  the other link return unauthorized :)

**Comment by Taer96** [comment]
+1 on the issues with the confluence page

**Comment by filipelautert** [comment]
Confluence is gone and we need to move the docs content somewhere else - probably to README file. Meanwhile it's available here: https://web.archive.org/web/20230922003222/https://liquibase.jira.com/wiki/spaces/CONTRIB/pages/3112975/Oracle+Extensions
