### ISSUE TITLE
Recent releases do not exist

### ISSUE THREAD

**Issue by doakd** [liquibase/liquibase-oracle#120]
The following are missing:
4.17.0
4.17.1
4.17.2
4.18.0

**Comment by filipelautert** [comment]
Hello! Thanks for advising, this will be fixed for 4.19 that will be released sometime this month.

**Comment by doakd** [comment]
We are always a few releases behind.  Can you fix this as of 4.17.2?

**Comment by filipelautert** [comment]
Hello @doakd ! I released 4.17.2 and it's already on maven central [1] (but I can't find it yet at mvnrepository, may take some time)
Could you ckeck if it's ok for you? Then I'll go ahead and release 4.18.0 too. 

1.  https://central.sonatype.dev/artifact/org.liquibase.ext/liquibase-oracle/4.17.2/overview

**Comment by doakd** [comment]
Can you please add it to this repo's releases?  My application build is set to get it from this repo.  Thanks.

**Comment by filipelautert** [comment]
Yeasp, it's a sloow mirroring process  :)

**Comment by filipelautert** [comment]
Fixed for 4.18 too, thanks for letting us know about this problem.
