### ISSUE TITLE
schemaName is not allowed on oracle

### ISSUE THREAD

**Issue by stefanborghys** [liquibase/liquibase-oracle#6]
Hey,

I'm having trouble executing a createTrigger script. It keeps returning following message: "schemaName is not allowed on oracle, ...".
I'm using dbchangelog-3.1.xsd and extention liquibase-oracle-3.0.0.jar against an Oracle XE database.
Strangely it works on another project using liquibases dbchangelog-2.0.xsd (don't know if this has something to do with it). I tried creating the trigger using sqlDeveloper and this works. Is there anything you could think of i'm doing wrong?
I also tried multiple combinations, names, with and without schemaName, but none of them works.

Command line output:
![liquibase_failed](https://f.cloud.github.com/assets/1375279/2131380/b6cc3bb6-929f-11e3-8eed-b1fe0b818ad8.png)

Databasechangelog:
![databasechangelog](https://f.cloud.github.com/assets/1375279/2131384/bef974ac-929f-11e3-8181-94a6e0fb82f0.png)

Create trigger changeset example:
![vote_id_trigger](https://f.cloud.github.com/assets/1375279/2131386/c6dcbeae-929f-11e3-8275-c4b5c6a4b872.png)

**Comment by safe42** [comment]
I have the latest version, 3.3, but I still get this error.
/Magnus

**Comment by stefanborghys** [comment]
Hey @safe42 

Since this bug had already been closed on 13/02/2014 i recommend you to post a new one,
If you are still having this issue.
