### ISSUE TITLE
Compilation fails on Java 16

### ISSUE THREAD

**Issue by AlecApp** [liquibase/liquibase-oracle#66]
Compiling on Java 16 (demonstrated in GitHub build action) fails with the following error:

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project liquibase-oracle: There are test failures.
```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1464) by [Unito](https://www.unito.io/learn-more)

**Comment by filipelautert** [comment]
Hi! thanks, it's working with java 17 now.
